apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-node-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-node-demo
  template:
    metadata:
      labels:
        app: jenkins-node-demo
    spec:
      containers:
        - name: jenkins-node-demo
          image: jenkins-node-demo:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000